# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 11:41
from __future__ import unicode_literals

from django.db import migrations
from worker import add_ratings


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_ratings),
    ]
