# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 14:59
from __future__ import unicode_literals

from django.db import migrations

from worker import add_ratings, add_program

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_ratings),
        migrations.RunPython(add_program),
    ]
