# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 11:49
from __future__ import unicode_literals

from django.db import migrations
from worker import add_program

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160722_1141'),
    ]

    operations = [
        migrations.RunPython(add_program),

    ]
