# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20160727_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_photos'),
        ),
    ]
