# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 04:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupQueue',
            new_name='FamilyQueue',
        ),
    ]
