# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160722_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Rating'),
        ),
    ]
