# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20160722_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue',
            name='program',
        ),
        migrations.AddField(
            model_name='queue',
            name='program',
            field=models.ManyToManyField(to='main.Program'),
        ),
    ]
