# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20160722_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(max_length=100)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Program')),
            ],
        ),
        migrations.RemoveField(
            model_name='queue',
            name='network',
        ),
        migrations.RemoveField(
            model_name='queue',
            name='program',
        ),
        migrations.AddField(
            model_name='network',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Queue'),
        ),
    ]
