# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160723_1719'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Network',
            new_name='QueueItems',
        ),
    ]
