# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 14:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20160724_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
